name: Build Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEF_FILE: "helloworld.def"
  OUTPUT_SIF: "helloworld.sif"
  LIBRARY_PATH: "library:josueneo/howto/helloworld:latest"
  SINGULARITY_VERSION: "3.10.2"
  SYLABS_AUTH_TOKEN: ${{ secrets.SYLABS_AUTH_TOKEN }}
  GOLANG_IMAGE: "library://josue-sylabs/devtools/golang:1.19.2"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    #- name: Set up Go
    #  uses: actions/setup-go@v3
    #  with:
    #    go-version: 1.18
    - name: Install singularity
      run: |
        wget https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce_${SINGULARITY_VERSION}-focal_amd64.deb
        sudo dpkg -i singularity-ce_${SINGULARITY_VERSION}-focal_amd64.deb

    - name: Build program
      run: singularity run $GOLANG_IMAGE go build -v -o helloworld ./cmd/main.go
    
    - name: Test program
      run: singularity run $GOLANG_IMAGE go test -v ./...
    
    - name: Prepare environment
      run: |
        #echo "USER_ID=$(id -u ${USER}):$(id -g ${USER})" >> $GITHUB_ENV
        mkdir -p ${{ github.workspace }}/tmp-sif-path
    
    - name: Build SIF image
      run: |
        singularity run docker://sylabsio/scs-build:latest build helloworld.def helloworld.sif

    - name: Scan source code with grype
      uses: anchore/scan-action@v3
      with:
        path: "${{ github.workspace }}"
        severity-cutoff: critical

    - name: Scan SIF with grype
      uses: anchore/scan-action@v3
      with:
        image: "singularity:${{ github.workspace }}/tmp-sif-path/${{ env.OUTPUT_SIF }}"
        severity-cutoff: critical

    - name: Save image and report to github
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.OUTPUT_SIF }}
        path: ${{ github.workspace }}/tmp-sif-path
